### ISSUE TITLE
Please add a big warning that the code is licensed under the "Microsoft Office Extensible File License"

### ISSUE THREAD

**Issue by redchair123** [stephen-hardy/DOCX.js#1]
Many people assume that code on github is open source, but that is far from the truth.  In fact, the Microsoft Office Extensible File License exemplifies Open Source Trolling: each clause an insult to the diligent readers' intellect.  

The real problem with all code under the license is that it muddies the water.  Microsoft could use your code as a reason to take legal action against others who genuinely try to innovate and use DOCX as a data format.  You hurt the community far more than you help by releasing pseudopen source code.  Ever think that those lawyers might _want_ you to do this so that they can go after others later on?

@stephen-hardy I think you are a reasonable person, and I might be niggling a bit, but neither of us want to see innovation stifled by myriads of lawsuits because one person's effort to release code created a miasma around a beloved software product.  Let this be a clarion call, and please share with your coworkers and superiors: unless the code can be released in a proper open source format, it's better that you don't release it.

**Comment by stephen-hardy** [comment]
I understand your argument, and I will modify the XLSX.js and DOCX.js pages to more prominently display the license. The association of GitHub with common open source licenses may suggest extra notification to the user in this case, but ultimately users are responsible for complying with the licenses of the code they choose to implement.

As for your direct comment, I appreciate your consideration of my position. I personally believe that those involved with the release of this code did so in order to foster innovation and good relations with the open source community - though you may not share my opinion. I will relate your conclusion in any future licensing discussions I participate in. However, your conclusion is your opinion, based upon the logic you have presented. I would argue that reasonable people can differ on whether it is beneficial to release code under the license in question. There was a time when Microsoft did not participate much in open source projects, and I'm happy to see that this code has been made available to the community. Perhaps the license will be re-examined some day.

Due to users' assumptions regarding the licensing of projects hosted on GitHub, I will explore other hosting options for future code released under a non-standard open source license. That may not fully address your concerns, but it should address some of the problems mentioned above.

**Comment by redchair123** [comment]
Why not just release it in CodePlex?  People will apply the requisite modicum of circumspection when seeing code hosted on CP.

**Comment by stephen-hardy** [comment]
We originally looked at CodePlex, but there are special MS-internal considerations for getting code hosted there. Definitely not impossible, but we didn't think (at the time) there was a reason to do that when GitHub would be quicker and easier. It is likely that we'll be looking to host code there in the future. 

I've added a warning to the description area. I'll be tweaking the description text and creating a readme over the next couple days.
